name: Trigger Workflow on File Change

on:
  push:
    paths:
      - 'file.xml'

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest


    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true                        
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'file.xml'
    
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'       # You need to update this path if you pass in a different output filename to the Dastardly action
          require_tests: true
          
