
name: Trigger on pomxml

on:
  push:
    paths:
      -'MyApp.java'
      -'/Users/amanaarmantrading/OneDrive - University of Bedfordshire/University of Bedfordshire/MyApp/'
      -'file.xml'

  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Read Target URL from file.xml
        id: read-target-url
        run: echo "name=GITHUB_OUTPUT::$(grep -oPm1 "(?<=<userText>)[^<]+" file.xml)"
      
      - uses: actions/checkout@v3
      - name: Run Dastardly Action Step
        continue-on-error: true                        
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: ${{ steps.read-target-url.outputs.url }}    

      - name: Publish Test Report
        if: always()                                    
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'   
          require_tests: true

